### ISSUE TITLE
Does readContractState support internal writes?

### ISSUE THREAD

**Issue by arcj0** [labscommunity/arweavekit#63]
If so, how do you set it to true?

**Comment by t8** [comment]
cc @ropats16 @7i7o

**Comment by pawanpaudel93** [comment]
Hello @arcj0, a new version `1.5.0` has been released which supports passing `evaluationOptions` to `readContractState`.

For example, you can pass `internalWrites` like this or any other supported options inside evaluationOptions.

```
const readResult = await readContractState({
  environment: "mainnet",
  contractTxId: "contract-transaction-id",
  evaluationOptions: {
    internalWrites: true,
  },
});

Please feel free to leave a comment if you encounter any issues.
```
