### ISSUE TITLE
Add support for custom configs of the Warp SDK

### ISSUE THREAD

**Issue by ropats16** [labscommunity/arweavekit#72]
This is a feature request to upgrade the contract utilities of arweavekit by adding support for custom warp configs :

- the ability to set evaluation options when creating a warp instance on the backend by taking in input params as an evaluation options object.
- the ability to disable bundling for being able to use the window object for contract interactions

**Comment by pawanpaudel93** [comment]
@ropats16 We have included this feature request in the recent PRs. So, I am closing this issue.
