### ISSUE TITLE
Roadmap Update Needed

### ISSUE THREAD

**Issue by amunrarara** [labscommunity/arweavekit#77]
Hey folks! 

Looks like the docs are just a tad bit behind; GraphQL and CLI support is now implemented, if I'm correct? See link, and keep on rockin'

https://docs.arweavekit.com/roadmap/features

**Comment by ropats16** [comment]
Hey thanks @amunrarara we have implemented the GraphQL features but the CLI support is still on the way. Updating the docs now

**Comment by ropats16** [comment]
Hey @amunrarara we have updated the Roadmap in the docs. You can view it here: https://docs.arweavekit.com/roadmap/features

Thanks for raising this!
