### ISSUE TITLE
[feat-request] dynamic gateway discovery

### ISSUE THREAD

**Issue by rosmcmahon** [labscommunity/arweavekit#79]
### Current gateway sources:
https://github.com/labscommunity/arweavekit/blob/11ec2269c936204132a7c8709fc09a469d6f28b8/src/utils.ts#L1-L6

### Suggestion
- Add ability to detect ARio GWs from the new registry. 
- Ref: https://github.com/ar-io/wayfinder

**Comment by rosmcmahon** [comment]
Yeah, I saw that. You wanna close this issue?

**Comment by ropats16** [comment]
Hey @rosmcmahon thanks! Closing this issue
